# Change all occurrences of "sample_validator" to your prerferred name
services:
  dedek168:
    container_name: dedek168
    # build: .
    image: "alloranetwork/allora-chain:v0.2.7"
    environment:
      - NETWORK=edgenet
      - MONIKER=dedek168
      - APP_HOME=./data
    volumes:
      - ./data:/data
      - ./scripts/:/scripts
    ports:
      - "26656-26657:26656-26657"
    user: "0:0"
    entrypoint: /scripts/l1_node.sh
